In [1]:
import pandas as pd

In [8]:
s = pd.read_csv('Annual_survey.csv')
s.tail()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
41704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41705,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41706,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41707,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41708,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
s.dropna()#drop all rows with NaN value

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021.0,Level 1,99999.0,All industries,Dollars (millions),H01,Total income,Financial performance,"7,57,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021.0,Level 1,99999.0,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"6,74,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021.0,Level 1,99999.0,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021.0,Level 1,99999.0,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021.0,Level 1,99999.0,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"6,54,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021.0,Level 1,99999.0,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
6,2021.0,Level 1,99999.0,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
7,2021.0,Level 1,99999.0,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
8,2021.0,Level 1,99999.0,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"1,23,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021.0,Level 1,99999.0,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021.0,Level 1,99999.0,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021.0,Level 1,99999.0,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"4,52,963",ANZSIC06 divisions A-S (excluding classes K633...
12,2021.0,Level 1,99999.0,All industries,Dollars (millions),H20,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
13,2021.0,Level 1,99999.0,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...
14,2021.0,Level 1,99999.0,All industries,Dollars (millions),H22,Closing stocks,Financial performance,"69,127",ANZSIC06 divisions A-S (excluding classes K633...
15,2021.0,Level 1,99999.0,All industries,Dollars (millions),H23,Surplus before income tax,Financial performance,"1,03,330",ANZSIC06 divisions A-S (excluding classes K633...
16,2021.0,Level 1,99999.0,All industries,Dollars (millions),H24,Total assets,Financial position,"25,12,677",ANZSIC06 divisions A-S (excluding classes K633...
17,2021.0,Level 1,99999.0,All industries,Dollars (millions),H25,Current assets,Financial position,"7,30,587",ANZSIC06 divisions A-S (excluding classes K633...
18,2021.0,Level 1,99999.0,All industries,Dollars (millions),H26,Fixed tangible assets,Financial position,"5,91,351",ANZSIC06 divisions A-S (excluding classes K633...

In [11]:
s.dropna(how = 'any')

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021.0,Level 1,99999.0,All industries,Dollars (millions),H01,Total income,Financial performance,"7,57,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021.0,Level 1,99999.0,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"6,74,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021.0,Level 1,99999.0,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021.0,Level 1,99999.0,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021.0,Level 1,99999.0,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"6,54,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021.0,Level 1,99999.0,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
6,2021.0,Level 1,99999.0,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
7,2021.0,Level 1,99999.0,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
8,2021.0,Level 1,99999.0,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"1,23,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021.0,Level 1,99999.0,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021.0,Level 1,99999.0,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021.0,Level 1,99999.0,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"4,52,963",ANZSIC06 divisions A-S (excluding classes K633...
12,2021.0,Level 1,99999.0,All industries,Dollars (millions),H20,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
13,2021.0,Level 1,99999.0,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...
14,2021.0,Level 1,99999.0,All industries,Dollars (millions),H22,Closing stocks,Financial performance,"69,127",ANZSIC06 divisions A-S (excluding classes K633...
15,2021.0,Level 1,99999.0,All industries,Dollars (millions),H23,Surplus before income tax,Financial performance,"1,03,330",ANZSIC06 divisions A-S (excluding classes K633...
16,2021.0,Level 1,99999.0,All industries,Dollars (millions),H24,Total assets,Financial position,"25,12,677",ANZSIC06 divisions A-S (excluding classes K633...
17,2021.0,Level 1,99999.0,All industries,Dollars (millions),H25,Current assets,Financial position,"7,30,587",ANZSIC06 divisions A-S (excluding classes K633...
18,2021.0,Level 1,99999.0,All industries,Dollars (millions),H26,Fixed tangible assets,Financial position,"5,91,351",ANZSIC06 divisions A-S (excluding classes K633...

In [12]:
s.dropna(how = 'all')

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2021.0,Level 1,99999.0,All industries,Dollars (millions),H01,Total income,Financial performance,"7,57,504",ANZSIC06 divisions A-S (excluding classes K633...
1,2021.0,Level 1,99999.0,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"6,74,890",ANZSIC06 divisions A-S (excluding classes K633...
2,2021.0,Level 1,99999.0,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"49,593",ANZSIC06 divisions A-S (excluding classes K633...
3,2021.0,Level 1,99999.0,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"33,020",ANZSIC06 divisions A-S (excluding classes K633...
4,2021.0,Level 1,99999.0,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"6,54,404",ANZSIC06 divisions A-S (excluding classes K633...
5,2021.0,Level 1,99999.0,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"26,138",ANZSIC06 divisions A-S (excluding classes K633...
6,2021.0,Level 1,99999.0,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,"6,991",ANZSIC06 divisions A-S (excluding classes K633...
7,2021.0,Level 1,99999.0,All industries,Dollars (millions),H11,Depreciation,Financial performance,"27,801",ANZSIC06 divisions A-S (excluding classes K633...
8,2021.0,Level 1,99999.0,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,"1,23,620",ANZSIC06 divisions A-S (excluding classes K633...
9,2021.0,Level 1,99999.0,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,275,ANZSIC06 divisions A-S (excluding classes K633...
10,2021.0,Level 1,99999.0,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,"2,085",ANZSIC06 divisions A-S (excluding classes K633...
11,2021.0,Level 1,99999.0,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"4,52,963",ANZSIC06 divisions A-S (excluding classes K633...
12,2021.0,Level 1,99999.0,All industries,Dollars (millions),H20,Non-operating expenses,Financial performance,"14,806",ANZSIC06 divisions A-S (excluding classes K633...
13,2021.0,Level 1,99999.0,All industries,Dollars (millions),H21,Opening stocks,Financial performance,"68,896",ANZSIC06 divisions A-S (excluding classes K633...
14,2021.0,Level 1,99999.0,All industries,Dollars (millions),H22,Closing stocks,Financial performance,"69,127",ANZSIC06 divisions A-S (excluding classes K633...
15,2021.0,Level 1,99999.0,All industries,Dollars (millions),H23,Surplus before income tax,Financial performance,"1,03,330",ANZSIC06 divisions A-S (excluding classes K633...
16,2021.0,Level 1,99999.0,All industries,Dollars (millions),H24,Total assets,Financial position,"25,12,677",ANZSIC06 divisions A-S (excluding classes K633...
17,2021.0,Level 1,99999.0,All industries,Dollars (millions),H25,Current assets,Financial position,"7,30,587",ANZSIC06 divisions A-S (excluding classes K633...
18,2021.0,Level 1,99999.0,All industries,Dollars (millions),H26,Fixed tangible assets,Financial position,"5,91,351",ANZSIC06 divisions A-S (excluding classes K633...